# Generated by Django 5.1.3 on 2025-09-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.book')),
                ('duration', models.DurationField()),
                ('file_format', models.CharField(choices=[('mp3', 'MP3'), ('wave', 'WAVE')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.book',),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.book')),
                ('page_count', models.PositiveIntegerField()),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('text', 'TEXT')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.book',),
        ),
        migrations.CreateModel(
            name='AvailableBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.book',),
        ),
    ]
